version: '2'

services:
  spring-app:
    image: transitproject/fine-grained-policy-machine:1.0
    restart: unless-stopped 
    command: "java -Xms2G -Xmx48G -Xss1G -jar /app/app.jar"
    environment:
      NEO4J_URI: 'bolt://access-control-fine-grained-neo:7687'
      NEO4J_USERNAME: ${NEO4J_USERNAME}
      NEO4J_PASSWORD: ${NEO4J_PASSWORD}
      API_PATH: '/api/v1'
    ports:
      - "8085:8085"
    depends_on:
      - access-control-fine-grained-neo
  
  access-control-fine-grained-neo:
    image: neo4j:5.16.0
    volumes_from:
      - access-control-fine-grained-volume-neo
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      - NEO4J_apoc_export_file_enabled=true
      - NEO4J_apoc_import_file_enabled=true
      - NEO4J_apoc_import_file_use__neo4j__config=true
      - NEO4J_PLUGINS=["apoc"]
      - NEO4J_dbms_security_procedures_unrestricted=apoc.*,algo.*
      - NEO4J_dbms_memory_heap_initial__size=512m
      - NEO4J_dbms_memory_heap_max__size=2G
      - NEO4J_apoc_uuid_enabled=true
      - NEO4J_dbms_default__listen__address=0.0.0.0
      - NEO4J_dbms_allow__upgrade=true
      - NEO4J_dbms_default__database=neo4j
      - NEO4J_AUTH=${NEO4J_USERNAME}/${NEO4J_PASSWORD}
    restart: unless-stopped

  access-control-fine-grained-volume-neo:
    image: rawmind/alpine-volume:0.0.2-4
    environment:
      SERVICE_GID: '7474'
      SERVICE_UID: '7474'
      SERVICE_VOLUME: /data
    network_mode: none
    volumes:
      - access-control-fine-grained-store-neo:/data

volumes:
  access-control-fine-grained-store-neo:
    driver: local

#docker-compose --env-file .env -p fine-grained-policy-machine -f docker-compose.yml up -d 


